//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsBacen
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS", ConfigurationName="wsBacen.FachadaWSSGS")]
    public interface FachadaWSSGS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<wsBacen.getValoresSeriesVOResponse> getValoresSeriesVOAsync(wsBacen.getValoresSeriesVORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<wsBacen.getUltimosValoresSerieVOResponse> getUltimosValoresSerieVOAsync(wsBacen.getUltimosValoresSerieVORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<wsBacen.getValoresSeriesXMLResponse> getValoresSeriesXMLAsync(wsBacen.getValoresSeriesXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<wsBacen.getUltimoValorVOResponse> getUltimoValorVOAsync(wsBacen.getUltimoValorVORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<wsBacen.getUltimoValorXMLResponse> getUltimoValorXMLAsync(wsBacen.getUltimoValorXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<wsBacen.getValorResponse> getValorAsync(wsBacen.getValorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<wsBacen.getValorEspecialResponse> getValorEspecialAsync(wsBacen.getValorEspecialRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://comum.ws.casosdeuso.sgs.pec.bcb.gov.br")]
    public partial class WSSerieVO
    {
        
        private int anoFimField;
        
        private int anoInicioField;
        
        private string avisoField;
        
        private int diaFimField;
        
        private int diaInicioField;
        
        private bool especialField;
        
        private string fonteField;
        
        private string fullNameField;
        
        private string gestorProprietarioField;
        
        private int mesFimField;
        
        private int mesInicioField;
        
        private string nomeAbreviadoField;
        
        private string nomeCompletoField;
        
        private long oidField;
        
        private string periodicidadeField;
        
        private string periodicidadeSiglaField;
        
        private bool possuiBloqueiosField;
        
        private bool publicaField;
        
        private string shortNameField;
        
        private WSValorSerieVO ultimoValorField;
        
        private string unidadePadraoField;
        
        private string unidadePadraoInglesField;
        
        private bool valorDiaNaoUtilField;
        
        private WSValorSerieVO[] valoresField;
        
        /// <remarks/>
        public int anoFim
        {
            get
            {
                return this.anoFimField;
            }
            set
            {
                this.anoFimField = value;
            }
        }
        
        /// <remarks/>
        public int anoInicio
        {
            get
            {
                return this.anoInicioField;
            }
            set
            {
                this.anoInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string aviso
        {
            get
            {
                return this.avisoField;
            }
            set
            {
                this.avisoField = value;
            }
        }
        
        /// <remarks/>
        public int diaFim
        {
            get
            {
                return this.diaFimField;
            }
            set
            {
                this.diaFimField = value;
            }
        }
        
        /// <remarks/>
        public int diaInicio
        {
            get
            {
                return this.diaInicioField;
            }
            set
            {
                this.diaInicioField = value;
            }
        }
        
        /// <remarks/>
        public bool especial
        {
            get
            {
                return this.especialField;
            }
            set
            {
                this.especialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fonte
        {
            get
            {
                return this.fonteField;
            }
            set
            {
                this.fonteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string gestorProprietario
        {
            get
            {
                return this.gestorProprietarioField;
            }
            set
            {
                this.gestorProprietarioField = value;
            }
        }
        
        /// <remarks/>
        public int mesFim
        {
            get
            {
                return this.mesFimField;
            }
            set
            {
                this.mesFimField = value;
            }
        }
        
        /// <remarks/>
        public int mesInicio
        {
            get
            {
                return this.mesInicioField;
            }
            set
            {
                this.mesInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nomeAbreviado
        {
            get
            {
                return this.nomeAbreviadoField;
            }
            set
            {
                this.nomeAbreviadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nomeCompleto
        {
            get
            {
                return this.nomeCompletoField;
            }
            set
            {
                this.nomeCompletoField = value;
            }
        }
        
        /// <remarks/>
        public long oid
        {
            get
            {
                return this.oidField;
            }
            set
            {
                this.oidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string periodicidade
        {
            get
            {
                return this.periodicidadeField;
            }
            set
            {
                this.periodicidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string periodicidadeSigla
        {
            get
            {
                return this.periodicidadeSiglaField;
            }
            set
            {
                this.periodicidadeSiglaField = value;
            }
        }
        
        /// <remarks/>
        public bool possuiBloqueios
        {
            get
            {
                return this.possuiBloqueiosField;
            }
            set
            {
                this.possuiBloqueiosField = value;
            }
        }
        
        /// <remarks/>
        public bool publica
        {
            get
            {
                return this.publicaField;
            }
            set
            {
                this.publicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string shortName
        {
            get
            {
                return this.shortNameField;
            }
            set
            {
                this.shortNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public WSValorSerieVO ultimoValor
        {
            get
            {
                return this.ultimoValorField;
            }
            set
            {
                this.ultimoValorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string unidadePadrao
        {
            get
            {
                return this.unidadePadraoField;
            }
            set
            {
                this.unidadePadraoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string unidadePadraoIngles
        {
            get
            {
                return this.unidadePadraoInglesField;
            }
            set
            {
                this.unidadePadraoInglesField = value;
            }
        }
        
        /// <remarks/>
        public bool valorDiaNaoUtil
        {
            get
            {
                return this.valorDiaNaoUtilField;
            }
            set
            {
                this.valorDiaNaoUtilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public WSValorSerieVO[] valores
        {
            get
            {
                return this.valoresField;
            }
            set
            {
                this.valoresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://comum.ws.casosdeuso.sgs.pec.bcb.gov.br")]
    public partial class WSValorSerieVO
    {
        
        private int anoField;
        
        private int anoFimField;
        
        private bool bloqueadoField;
        
        private bool bloqueioLiberadoField;
        
        private int diaField;
        
        private int diaFimField;
        
        private int mesField;
        
        private int mesFimField;
        
        private long oidField;
        
        private long oidSerieField;
        
        private string svalorField;
        
        private System.Nullable<decimal> valorField;
        
        /// <remarks/>
        public int ano
        {
            get
            {
                return this.anoField;
            }
            set
            {
                this.anoField = value;
            }
        }
        
        /// <remarks/>
        public int anoFim
        {
            get
            {
                return this.anoFimField;
            }
            set
            {
                this.anoFimField = value;
            }
        }
        
        /// <remarks/>
        public bool bloqueado
        {
            get
            {
                return this.bloqueadoField;
            }
            set
            {
                this.bloqueadoField = value;
            }
        }
        
        /// <remarks/>
        public bool bloqueioLiberado
        {
            get
            {
                return this.bloqueioLiberadoField;
            }
            set
            {
                this.bloqueioLiberadoField = value;
            }
        }
        
        /// <remarks/>
        public int dia
        {
            get
            {
                return this.diaField;
            }
            set
            {
                this.diaField = value;
            }
        }
        
        /// <remarks/>
        public int diaFim
        {
            get
            {
                return this.diaFimField;
            }
            set
            {
                this.diaFimField = value;
            }
        }
        
        /// <remarks/>
        public int mes
        {
            get
            {
                return this.mesField;
            }
            set
            {
                this.mesField = value;
            }
        }
        
        /// <remarks/>
        public int mesFim
        {
            get
            {
                return this.mesFimField;
            }
            set
            {
                this.mesFimField = value;
            }
        }
        
        /// <remarks/>
        public long oid
        {
            get
            {
                return this.oidField;
            }
            set
            {
                this.oidField = value;
            }
        }
        
        /// <remarks/>
        public long oidSerie
        {
            get
            {
                return this.oidSerieField;
            }
            set
            {
                this.oidSerieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string svalor
        {
            get
            {
                return this.svalorField;
            }
            set
            {
                this.svalorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> valor
        {
            get
            {
                return this.valorField;
            }
            set
            {
                this.valorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getValoresSeriesVO", WrapperNamespace="http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br", IsWrapped=true)]
    public partial class getValoresSeriesVORequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long[] in0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string in1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string in2;
        
        public getValoresSeriesVORequest()
        {
        }
        
        public getValoresSeriesVORequest(long[] in0, string in1, string in2)
        {
            this.in0 = in0;
            this.in1 = in1;
            this.in2 = in2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getValoresSeriesVOResponse", WrapperNamespace="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS", IsWrapped=true)]
    public partial class getValoresSeriesVOResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public wsBacen.WSSerieVO[] getValoresSeriesVOReturn;
        
        public getValoresSeriesVOResponse()
        {
        }
        
        public getValoresSeriesVOResponse(wsBacen.WSSerieVO[] getValoresSeriesVOReturn)
        {
            this.getValoresSeriesVOReturn = getValoresSeriesVOReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUltimosValoresSerieVO", WrapperNamespace="http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br", IsWrapped=true)]
    public partial class getUltimosValoresSerieVORequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long in0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public long in1;
        
        public getUltimosValoresSerieVORequest()
        {
        }
        
        public getUltimosValoresSerieVORequest(long in0, long in1)
        {
            this.in0 = in0;
            this.in1 = in1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUltimosValoresSerieVOResponse", WrapperNamespace="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS", IsWrapped=true)]
    public partial class getUltimosValoresSerieVOResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public wsBacen.WSSerieVO getUltimosValoresSerieVOReturn;
        
        public getUltimosValoresSerieVOResponse()
        {
        }
        
        public getUltimosValoresSerieVOResponse(wsBacen.WSSerieVO getUltimosValoresSerieVOReturn)
        {
            this.getUltimosValoresSerieVOReturn = getUltimosValoresSerieVOReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getValoresSeriesXML", WrapperNamespace="http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br", IsWrapped=true)]
    public partial class getValoresSeriesXMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long[] in0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string in1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string in2;
        
        public getValoresSeriesXMLRequest()
        {
        }
        
        public getValoresSeriesXMLRequest(long[] in0, string in1, string in2)
        {
            this.in0 = in0;
            this.in1 = in1;
            this.in2 = in2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getValoresSeriesXMLResponse", WrapperNamespace="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS", IsWrapped=true)]
    public partial class getValoresSeriesXMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string getValoresSeriesXMLReturn;
        
        public getValoresSeriesXMLResponse()
        {
        }
        
        public getValoresSeriesXMLResponse(string getValoresSeriesXMLReturn)
        {
            this.getValoresSeriesXMLReturn = getValoresSeriesXMLReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUltimoValorVO", WrapperNamespace="http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br", IsWrapped=true)]
    public partial class getUltimoValorVORequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long in0;
        
        public getUltimoValorVORequest()
        {
        }
        
        public getUltimoValorVORequest(long in0)
        {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUltimoValorVOResponse", WrapperNamespace="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS", IsWrapped=true)]
    public partial class getUltimoValorVOResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public wsBacen.WSSerieVO getUltimoValorVOReturn;
        
        public getUltimoValorVOResponse()
        {
        }
        
        public getUltimoValorVOResponse(wsBacen.WSSerieVO getUltimoValorVOReturn)
        {
            this.getUltimoValorVOReturn = getUltimoValorVOReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUltimoValorXML", WrapperNamespace="http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br", IsWrapped=true)]
    public partial class getUltimoValorXMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long in0;
        
        public getUltimoValorXMLRequest()
        {
        }
        
        public getUltimoValorXMLRequest(long in0)
        {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUltimoValorXMLResponse", WrapperNamespace="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS", IsWrapped=true)]
    public partial class getUltimoValorXMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string getUltimoValorXMLReturn;
        
        public getUltimoValorXMLResponse()
        {
        }
        
        public getUltimoValorXMLResponse(string getUltimoValorXMLReturn)
        {
            this.getUltimoValorXMLReturn = getUltimoValorXMLReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getValor", WrapperNamespace="http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br", IsWrapped=true)]
    public partial class getValorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long in0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string in1;
        
        public getValorRequest()
        {
        }
        
        public getValorRequest(long in0, string in1)
        {
            this.in0 = in0;
            this.in1 = in1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getValorResponse", WrapperNamespace="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS", IsWrapped=true)]
    public partial class getValorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public decimal getValorReturn;
        
        public getValorResponse()
        {
        }
        
        public getValorResponse(decimal getValorReturn)
        {
            this.getValorReturn = getValorReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getValorEspecial", WrapperNamespace="http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br", IsWrapped=true)]
    public partial class getValorEspecialRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long in0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string in1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string in2;
        
        public getValorEspecialRequest()
        {
        }
        
        public getValorEspecialRequest(long in0, string in1, string in2)
        {
            this.in0 = in0;
            this.in1 = in1;
            this.in2 = in2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getValorEspecialResponse", WrapperNamespace="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS", IsWrapped=true)]
    public partial class getValorEspecialResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public decimal getValorEspecialReturn;
        
        public getValorEspecialResponse()
        {
        }
        
        public getValorEspecialResponse(decimal getValorEspecialReturn)
        {
            this.getValorEspecialReturn = getValorEspecialReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public interface FachadaWSSGSChannel : wsBacen.FachadaWSSGS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public partial class FachadaWSSGSClient : System.ServiceModel.ClientBase<wsBacen.FachadaWSSGS>, wsBacen.FachadaWSSGS
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FachadaWSSGSClient() : 
                base(FachadaWSSGSClient.GetDefaultBinding(), FachadaWSSGSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.FachadaWSSGS.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FachadaWSSGSClient(EndpointConfiguration endpointConfiguration) : 
                base(FachadaWSSGSClient.GetBindingForEndpoint(endpointConfiguration), FachadaWSSGSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FachadaWSSGSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FachadaWSSGSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FachadaWSSGSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FachadaWSSGSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FachadaWSSGSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsBacen.getValoresSeriesVOResponse> wsBacen.FachadaWSSGS.getValoresSeriesVOAsync(wsBacen.getValoresSeriesVORequest request)
        {
            return base.Channel.getValoresSeriesVOAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsBacen.getValoresSeriesVOResponse> getValoresSeriesVOAsync(long[] in0, string in1, string in2)
        {
            wsBacen.getValoresSeriesVORequest inValue = new wsBacen.getValoresSeriesVORequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            inValue.in2 = in2;
            return ((wsBacen.FachadaWSSGS)(this)).getValoresSeriesVOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsBacen.getUltimosValoresSerieVOResponse> wsBacen.FachadaWSSGS.getUltimosValoresSerieVOAsync(wsBacen.getUltimosValoresSerieVORequest request)
        {
            return base.Channel.getUltimosValoresSerieVOAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsBacen.getUltimosValoresSerieVOResponse> getUltimosValoresSerieVOAsync(long in0, long in1)
        {
            wsBacen.getUltimosValoresSerieVORequest inValue = new wsBacen.getUltimosValoresSerieVORequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            return ((wsBacen.FachadaWSSGS)(this)).getUltimosValoresSerieVOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsBacen.getValoresSeriesXMLResponse> wsBacen.FachadaWSSGS.getValoresSeriesXMLAsync(wsBacen.getValoresSeriesXMLRequest request)
        {
            return base.Channel.getValoresSeriesXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsBacen.getValoresSeriesXMLResponse> getValoresSeriesXMLAsync(long[] in0, string in1, string in2)
        {
            wsBacen.getValoresSeriesXMLRequest inValue = new wsBacen.getValoresSeriesXMLRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            inValue.in2 = in2;
            return ((wsBacen.FachadaWSSGS)(this)).getValoresSeriesXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsBacen.getUltimoValorVOResponse> wsBacen.FachadaWSSGS.getUltimoValorVOAsync(wsBacen.getUltimoValorVORequest request)
        {
            return base.Channel.getUltimoValorVOAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsBacen.getUltimoValorVOResponse> getUltimoValorVOAsync(long in0)
        {
            wsBacen.getUltimoValorVORequest inValue = new wsBacen.getUltimoValorVORequest();
            inValue.in0 = in0;
            return ((wsBacen.FachadaWSSGS)(this)).getUltimoValorVOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsBacen.getUltimoValorXMLResponse> wsBacen.FachadaWSSGS.getUltimoValorXMLAsync(wsBacen.getUltimoValorXMLRequest request)
        {
            return base.Channel.getUltimoValorXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsBacen.getUltimoValorXMLResponse> getUltimoValorXMLAsync(long in0)
        {
            wsBacen.getUltimoValorXMLRequest inValue = new wsBacen.getUltimoValorXMLRequest();
            inValue.in0 = in0;
            return ((wsBacen.FachadaWSSGS)(this)).getUltimoValorXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsBacen.getValorResponse> wsBacen.FachadaWSSGS.getValorAsync(wsBacen.getValorRequest request)
        {
            return base.Channel.getValorAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsBacen.getValorResponse> getValorAsync(long in0, string in1)
        {
            wsBacen.getValorRequest inValue = new wsBacen.getValorRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            return ((wsBacen.FachadaWSSGS)(this)).getValorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsBacen.getValorEspecialResponse> wsBacen.FachadaWSSGS.getValorEspecialAsync(wsBacen.getValorEspecialRequest request)
        {
            return base.Channel.getValorEspecialAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsBacen.getValorEspecialResponse> getValorEspecialAsync(long in0, string in1, string in2)
        {
            wsBacen.getValorEspecialRequest inValue = new wsBacen.getValorEspecialRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            inValue.in2 = in2;
            return ((wsBacen.FachadaWSSGS)(this)).getValorEspecialAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FachadaWSSGS))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FachadaWSSGS))
            {
                return new System.ServiceModel.EndpointAddress("https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return FachadaWSSGSClient.GetBindingForEndpoint(EndpointConfiguration.FachadaWSSGS);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return FachadaWSSGSClient.GetEndpointAddress(EndpointConfiguration.FachadaWSSGS);
        }
        
        public enum EndpointConfiguration
        {
            
            FachadaWSSGS,
        }
    }
}
